# pull official base image
FROM python:3.8-alpine

# accept arguments
ARG PIP_REQUIREMENTS=dev.txt

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


RUN mkdir /app
# set work directory
WORKDIR /app

# copy and install pip requirements
COPY ./src/requirements/ /app/requirements/
RUN pip install -r /app/requirements/dev.txt

# copy Django project files
COPY ./src /app